### ISSUE TITLE
IPHLPAPI.DLL dependence in Windows XP

### ISSUE THREAD

**Issue by dvdmena** [openslide/openslide-winbuild#7]
Hi:

I have downloaded the binary for win64 (20150527) to use with Python. 

When I try to execute a python script I have a 127 Error: The specified procedure could not be found. (not path problem) 

When I try to execute a binary like openslide-show-properties I have a Entry Point Not Found Error: The procedure entry point if_nametoindex could not be located in the dynamic link library IPHLPAPI.DLL

I have the suspect that the library version i have in the Windows XP 64 SP2 could be an old version.

**Comment by bgilbert** [comment]
Thanks for the report.  Our GLib builds depend on `if_nametoindex`, which is not available in Windows XP.  I believe that dependency can be disabled at compile-time.  Our build script also includes some [workarounds](https://github.com/openslide/openslide-winbuild/blob/0b49b8d3ca0eb9e49e104d97893a4e504a4004a8/build.sh#L499) for GLib build problems, which may be forcing GLib to use `if_nametoindex` when it would not otherwise do so.

Windows XP is out of security support, so I don't expect that we'll fix this upstream.  However, you may be able to fix it yourself by modifying `build.sh` and rebuilding.  If so, please post your modifications here so they can be used by others.

**Comment by Markus-PP** [comment]
I got this to work under Windows XP by commenting out the sed substitutes in the glib) section of function build_one(). Nothing else changed.

```
    glib)
        # https://bugzilla.gnome.org/show_bug.cgi?id=754431
        sed -i 's/#include "config.h"/&\n#define MINGW_HAS_SECURE_API 1/' \
                glib/gstrfuncs.c
        do_configure \
                --with-threads=win32
        # Fix 32-bit Cygwin builds in a uniform way
        # https://bugzilla.gnome.org/show_bug.cgi?id=739656
#        sed -i 's/#include "config.h"/\0\n#undef _WIN32_WINNT\n#define _WIN32_WINNT 0x0600/' \
#                gio/gsocket.c
#        sed -i -e "s/.*HAVE_IF_INDEXTONAME.*/#define HAVE_IF_INDEXTONAME 1/" \
#                -e "s/.*HAVE_IF_NAMETOINDEX.*/#define HAVE_IF_NAMETOINDEX 1/"\
#                config.h
        make $parallel
        make install
        ;;
```

**Comment by bgilbert** [comment]
@Markus-PP Those sed substitutions are apparently not necessary with current glib, so I removed them in 459b16ea90a1801a8fad1009fc6371326fb67d28.  So, current nightly builds may work again on Windows XP.
