### ISSUE TITLE
objcopy strips the string table from the DLLs

### ISSUE THREAD

**Issue by GeertLitjens** [openslide/openslide-winbuild#8]
After the build, objcopy is used generate seperate debug libraries. However, on Windows the strip-all option (-S) also strips the string table, which causes issues when using for example dumpbin to analyze the DLL. I think this can simply be fixed by using -g option for objcopy (removes only debug symbols from the dll), this at least leaves the string table intact.

**Comment by bgilbert** [comment]
It seems to be common practice on Windows (as on Unix) to strip the symbol table from release builds.  The symbols are still available from the `.dll.debug` file; can you run dumpbin on that instead?

**Comment by GeertLitjens** [comment]
Well, -g still strips all the debug symbols, but leaves the string table. At leas in most of the DLLs I tested on Windows, this table seems to present. Don't know for Unix based systems though.

**Comment by bgilbert** [comment]
The **string table** is still present; it's necessary to represent the `.gnu_debuglink` section name (since that is longer than 8 characters).  The `/4` in the output of `dumpbin` is a reference to the string table:

```
SECTION HEADER #B
      /4 name (.gnu_debuglink)
```

The **symbol table** is indeed removed.  I've run `dumpbin /symbols` on a number of random DLLs on a Windows system and none of them have symbols, so this does indeed seem to be common practice.  I've verified that you can still get the symbols by running `dumpbin /symbols` on the corresponding `.dll.debug` file.  This is all with Visual Studio 2015.

If you're trying to debug OpenSlide on Windows, you'll probably want to use GDB in any case, since MinGW writes debug symbols in a format Visual Studio can't read.  GDB should automatically read the `.dll.debug` files if they are kept in the same directory as the DLLs.
