### ISSUE TITLE
read_region crashes due to stack misalignment in win32

### ISSUE THREAD

**Issue by Markus-PP** [openslide/openslide-winbuild#9]
In our case, this happens only when using the BIF format. At some point, a SEGV occurs.
It's in file openslide-vendor-ventana.c line 212
When it crashes, GDB leads me to the diassembly below in a function using SSE code.
At point of crash, register ESP contains an odd number 0x.......c. not suitable for an SSE instruction that demands 16-bit alignment.

```
static bool read_subtile(openslide_t *osr, ...)
{
...
  cairo_set_source_surface(cr2, surface, -subtile_x, -subtile_y);
...
0x64f9d98b  mulsd  0x40(%esp),%xmm0
0x64f9d991  mov    0x50(%esp),%eax
0x64f9d995  mov    %edx,0xc(%esp)
0x64f9d999  mov    0x54(%esp),%edx
===>0x64f9d99d  movaps %xmm2,0x40(%esp)<=== access violation
0x64f9d9a2  mov    %eax,(%esp)
0x64f9d9a5  xorpd  %xmm2,%xmm0
0x64f9d9a9  mov    %edx,0x4(%esp)
0x64f9d9ad  movsd  %xmm0,0x10(%esp)
0x64f9d9b3  call   0x64fa17f0 <__moddi3>
0x64f9d9b8  mov    %edx,0x54(%esp)
...
}
```
To prevent this, I changed the build.sh - In section openslide) I added the line 

`CFLAGS="-mincoming-stack-boundary=2" `

so gcc would account for the WIN32's 4-byte stack alignment.
After recompiling, the error wouldn't occur any more.
Is this "the right way" to solve this problem ?

```
function build_one() 
{
...
    openslide)
        local ver_suffix_arg
        if [ -n "${ver_suffix}" ] ; then
            ver_suffix_arg="--with-version-suffix=${ver_suffix}"
        fi
        do_configure \
                "${ver_suffix_arg}" \
                CFLAGS="-mincoming-stack-boundary=2"
        make $parallel
        if [ "$can_test" = yes ] ; then
            make check
        fi
        make install
        ;;

```

**Comment by bgilbert** [comment]
Thanks for the report!  For the record (and as you've already discovered) the problem is that GCC intentionally assumes that stack frames are aligned to 16 bytes, even though the Win32 ABI only requires 4-byte alignment.  That works until GCC emits aligned moves between the stack and SSE registers, and OpenSlide is called from code compiled by MSVC.  This may also explain the autovectorization crashes we were seeing [last year](https://github.com/openslide/openslide-winbuild/commit/550ef14b4a7cbac76748ce9a1377b8ee302643c0).  The Win64 ABI specifies 16-byte alignment and is not affected.

The smallest possible fix would be to add `__attribute__((force_align_arg_pointer))` to every `dllexport` function in OpenSlide, and use no new compiler options.  However, I'm concerned that that approach would be too brittle: if any of the other libraries ever performed floating-point or autovectorized math in a callback invoked via operating system code, it would lead to GPFs which would be difficult to track down.  So I'm inclined to protect all of the libraries we build, not just OpenSlide or the OpenSlide entry points.

In that case, we can use `-mstackrealign` instead of `-mincoming-stack-boundary=2`.  This will emit the stack realignment prologue only for functions which require the larger alignment, rather than emitting it unconditionally.  We couldn't do this if we were only protecting libopenslide, since OpenSlide would need to ensure that the stack was always realigned before calling into other libraries.
